### ISSUE TITLE
Change order in dragArea

### ISSUE THREAD

**Issue by alanRiveros** [m-inan/react-upload-gallery#11]
When I drop a file the DragArea put the file first in the list, 
![image](https://user-images.githubusercontent.com/8962288/89045535-11405900-d322-11ea-8b39-f0e69305c2eb.png)
but I want to put the new file last in the list. 
![image](https://user-images.githubusercontent.com/8962288/89045631-33d27200-d322-11ea-844d-0867f1922dcc.png)
There is any config to make that possible?
Thankyou

**Comment by m-inan** [comment]
The feature has been added and can be used with the next version `v0.1.1`. This is the sample code for use.
```js
<Rug
  inOrder={true} // add this prop
  ...
/>
```

**Comment by alanRiveros** [comment]
@m-inan thank you for this feature
