### ISSUE TITLE
multiple files

### ISSUE THREAD

**Issue by alanRiveros** [m-inan/react-upload-gallery#12]
Hi, I've noticed that in the new release '0.1.1' when I select multiple files on dialog in the gallery just show the last, in the previous version '0.1.0' this feature work normally
thankyou

**Comment by khanhpro9889** [comment]
Same issue

**Comment by ivantoniev-daughter** [comment]
It looks like it's this line that broke it https://github.com/m-inan/react-upload-gallery/commit/0d2b03b462843054ba39c530ea63c363db70c7c2#diff-7556efc3eec1e2ccd1fb993ad571196eR433. The commit states "Upload the same file multiple times" but I'm not sure how that'd work unless you reopen the file selector multiple times

**Comment by ivantoniev-daughter** [comment]
@m-inan Thanks for sorting this out 🙂

**Comment by alanRiveros** [comment]
Thanks =D
