### ISSUE TITLE
Not possible to use onSortEnd sorting callback

### ISSUE THREAD

**Issue by IvanAddolorato** [m-inan/react-upload-gallery#14]
Hello @m-inan 

First, I want to thank you for such a great component. It is very flexible and easy to use.

This issue is due the impossibility to use the sorting callback onSortEnd, as it explicitly overriden in the line referenced below:

https://github.com/m-inan/react-upload-gallery/blob/e21bdeb76e68dbedbc0b7e34ae27f520bf2392b0/src/DragArea.js#L19

I think that this can be solved by doing something like:

`
onSortEnd={(params, e) => {
     setSort(arrayMove(images, params.oldIndex, params.newIndex));
     props.onSortEnd(params, e);
}}
`

What do you think?

Thanks and looking forward for an answer.

Ivan.-

**Comment by m-inan** [comment]
@IvanAddolorato  Do you just want callbacks here or do you need with data ? Like `oldIndex`, `newIndex`

**Comment by IvanAddolorato** [comment]
Thanks for quick reply.

I need the data to make some actions based on it.

**Comment by m-inan** [comment]
@IvanAddolorato  You can use it this way. https://github.com/m-inan/react-upload-gallery/commit/a2090a2855e01bc79ae9fdd5e58043dd5957b663
```tsx
<Rug
  onSortEnd={(images: any, diff: any) => {
    console.log(images, diff);
  }}
/>
```
I would be very glad if you can test it on the last commit and return it. Then I can add the feature to the document and send it as a new package.

**Comment by IvanAddolorato** [comment]
I have just tested it and works perfect. 

From my side, this is ready to be packaged and released.

Thanks so much!

**Comment by m-inan** [comment]
Thanks for the suggestion. You can use the feature with the `0.2.0` version.

**Comment by IvanAddolorato** [comment]
Great!
