### ISSUE TITLE
Image not rendering.

### ISSUE THREAD

**Issue by MahekPandya** [m-inan/react-upload-gallery#15]
Hello,
I am facing an issue in displaying the uploaded images. Following is the code and output I am getting.
` const initialState = [
    {
      source: imgsrc[0],
    },
    {
      source:     "http://abc/uploads/2020/09/sandwich-upper-2-3-1.png",
    }
  ];`
Output I am getting:

![Capture](https://user-images.githubusercontent.com/58770031/95899033-8bbf3780-0dad-11eb-8475-fc8a91511bf3.PNG)

** imgsrc[0] is not null.**

**Comment by m-inan** [comment]
@MahekPandya Can you add console and network outputs?
