### ISSUE TITLE
Hide input choose File

### ISSUE THREAD

**Issue by kiranmaya** [m-inan/react-upload-gallery#18]
im following custom request example .How to hide input field ?
![Screenshot_29](https://user-images.githubusercontent.com/3712631/106393111-286c1a80-641b-11eb-8842-7d7e07f51a93.png)

**Comment by m-inan** [comment]
Hi @kiranmaya, I'm sorry I made a late turn. If you could not solve the problem, is it possible to prepare a sample? I need to see exactly where the problem occurs

**Comment by kiranmaya** [comment]
Your example scripts work fine, I did something wrong . currently getting an error for the material UI package in the code sandbox, will try some other site to show my component.

**Comment by m-inan** [comment]
@kiranmaya You can use this address to test codes https://codesandbox.io/. If you get any errors, feel free to write.
