### ISSUE TITLE
In case of mutli upload images (by batch) i cant catch the name(s) of the file(s) do not pass the rules ...

### ISSUE THREAD

**Issue by arti-kland** [m-inan/react-upload-gallery#19]
Hi,

I m trying to indicate to my users witch file(s) break the rules to uploade, then i can add the name of this file in the message error

exemple : "[file name], [file name] errorMesage" !

For the rest your component work so well thanks so mutch !

**Comment by m-inan** [comment]
Hi, @arti-kland. You can get the file name as in the example. You can group each incoming alert by type and edit the error message with the file names. If this is not what you want, please prepare a sample structure.
```
onWarning={(type, rules) => {
  console.log(type, rules, rules.file.name);
}
```

**Comment by arti-kland** [comment]
Thx for you response m-mian !
