### ISSUE TITLE
Remove Images Manually

### ISSUE THREAD

**Issue by ShaheryarAbid** [m-inan/react-upload-gallery#22]
How do I remove an image manually through code. For example... I am right now running "onConfirmDelete" function... in that function, I send the images in the parent component... remove the current Image by checking some conditions in the parent component State... 

Now the image is being removed in the parent component state... which is then given to RUG component as initialState.... but it is surely not removing the image from RUG as I can not find anything in the documentation to update the images array manually rather than RUG removing the image itself.

How can I provide the updated images array to the RUG component just like initialState ?

```
Parent Component State = {
    imageGallery: [ list of images here....]
}
```

```
RUG component state = {
        initialState: [...this.props.imageGallery]
}
```

// The RUG Component
```
<RUG
                    rules={{
                        limit: 10,
                    }}
                    accept={['jpg', 'jpeg', 'png']}
                    autoUpload={false}
                    sorting={{ lockAxis: 'x' }}
                    initialState={this.state.initialState}
                    onChange={this.onImageChange}
                    onConfirmDelete={this.onConfirmDelete}
  />
```

// Functions in RUG Component

```
onImageChange = (image) => {
        //   I call the addImages function in the parent component and pass all the images list to it... 
        //   so that it can change the state of the parent component and add the images there whenever 
        //    any images have been added
        this.props.addImages(image, "imageGallery");
}


onConfirmDelete = (currentImage, images) => {
        //   I want to check some conditions before I delete any image... so I call a function in the parent component....
        this.props.removeImage(currentImage, images, "imageGallery");

        //   In that function... If the conditions are met... 
        //   I delete the currentImage from that component's state  (the parent component's state)...
       //    Which is being deleted properly. 
       //    But I can not update the image gallery in this RUG component, after I delete the image in the parent component's state
      //     Because changes in the parent component state... which is connected to RUG as initialState... will not run onImageChange function
}
```

Let me know how can I update the images list from outside the RUG component...

Thanks.

**Comment by m-inan** [comment]
Hi @ShaheryarAbid.
Yes, there is no direct solution in the documentation for this. But we can solve this using React References.

Sample Code

```js
import React, { useRef } from 'react';

function App () {
  const ref = useRef();

  removeImage(image) {
    // Rug remove method
    ref.current.remove(image.uid);
  }
  
  return (
    <Rug ref={ref} .... />
  )
}
```

I think it will work that way.

**Comment by ShaheryarAbid** [comment]
Hi @m-inan That solution did not work for me....

So what I did is to re-render RUG component everytime I remove the image from the images list in the parent component.

**Comment by modbender** [comment]
@ShaheryarAbid Simple solution actually, you can directly set state of this component since it's a class.

```js
const removeAllImages = (e) => {
    ref.current.setState({ images: [] });
  };
```

Basically `ref.current` is same as using `this` inside class.
