### ISSUE TITLE
Video support

### ISSUE THREAD

**Issue by IvanAddolorato** [m-inan/react-upload-gallery#23]
Hello @m-inan, I'm wondering if it is possible to use this component for images and videos too. Is there any way? If not, do you think is a nice feature to add?

Thanks!

**Comment by m-inan** [comment]
I guess I need to redesign the structure for that. You need to find a better alternative to upload videos. I'm sorry for this

**Comment by IvanAddolorato** [comment]
ok, thanks for answering!
