### ISSUE TITLE
Disable automatic upload in action attribute

### ISSUE THREAD

**Issue by ZenStudioLab** [m-inan/react-upload-gallery#30]
I have tried to set ```action={null}```, or leaving it empty, but to no avail.
Is this possible to achieve this?

**Comment by m-inan** [comment]
@zenzjtech If you want to do the download not automatically but with a button, this prop will work for you. 
```js
<Rug
  ...
  autoUpload={false}
/>

```

**Comment by zenzjtech** [comment]
Yes it works!
