### ISSUE TITLE
types declaration

### ISSUE THREAD

**Issue by dorumrr** [m-inan/react-upload-gallery#9]
When using it with typescript it complains about the missing types. Any chance to add @types/react-upload-gallery or a .d.ts declaration file?

Thanks and keep up the good work!

**Comment by m-inan** [comment]
I added a temporary file to work in typescript. however, it will be updated with the file containing all types in the near future.  Refs: https://github.com/m-inan/react-upload-gallery/commit/00f232c32fbb6bd69a700f03022321135a579c94
